"""org members

Revision ID: 1fa4c43252d7
Revises: 
Create Date: 2025-11-01 20:46:49.690407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa4c43252d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape',
    sa.Column('scrape_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scrape_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('friend_a', sa.BigInteger(), nullable=False),
    sa.Column('friend_b', sa.BigInteger(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_a'], ['user.user_id'], name='fk_friends_friend_a_user_user_id'),
    sa.ForeignKeyConstraint(['friend_b'], ['user.user_id'], name='fk_friends_friend_b_user_user_id'),
    sa.PrimaryKeyConstraint('friend_a', 'friend_b')
    )
    op.create_table('org',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], name='fk_org_creator_id_user_user_id'),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('opportunity',
    sa.Column('opp_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.org_id'], name='fk_opportunity_org_id_org_org_id'),
    sa.PrimaryKeyConstraint('opp_id')
    )
    op.create_table('org_member',
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.org_id'], name='fk_org_member_org_id_org_org_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='fk_org_member_user_id_user_user_id'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('pledge',
    sa.Column('pledge_id', sa.BigInteger(), nullable=False),
    sa.Column('opp_id', sa.BigInteger(), nullable=True),
    sa.Column('scrape_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['opp_id'], ['opportunity.opp_id'], name='fk_pledge_opp_id_opportunity_opp_id'),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.scrape_id'], name='fk_pledge_scrape_id_scrape_scrape_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='fk_pledge_user_id_user_user_id'),
    sa.PrimaryKeyConstraint('pledge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pledge')
    op.drop_table('org_member')
    op.drop_table('opportunity')
    op.drop_table('org')
    op.drop_table('friends')
    op.drop_table('user')
    op.drop_table('scrape')
    # ### end Alembic commands ###
