"""rename request to opportunity

Revision ID: 48457365b1b3
Revises: 1075f025e11b
Create Date: 2025-11-01 19:11:21.500471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48457365b1b3'
down_revision = '1075f025e11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('opp_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.org_id'], name='fk_opportunity_org_id_org_org_id'),
    sa.PrimaryKeyConstraint('opp_id')
    )
    op.drop_table('request')
    with op.batch_alter_table('pledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opp_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_pledge_opp_id_opportunity_opp_id', 'opportunity', ['opp_id'], ['opp_id'])
        batch_op.drop_column('request_id')

    with op.batch_alter_table('promotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opp_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_promotes_opp_id_opportunity_opp_id', 'opportunity', ['opp_id'], ['opp_id'])
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.BIGINT(), nullable=True))
        batch_op.drop_constraint('fk_promotes_opp_id_opportunity_opp_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['request_id'])
        batch_op.drop_column('opp_id')

    with op.batch_alter_table('pledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.BIGINT(), nullable=True))
        batch_op.drop_constraint('fk_pledge_opp_id_opportunity_opp_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['request_id'])
        batch_op.drop_column('opp_id')

    op.create_table('request',
    sa.Column('request_id', sa.BIGINT(), nullable=False),
    sa.Column('org_id', sa.BIGINT(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.org_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.drop_table('opportunity')
    # ### end Alembic commands ###
