"""initial migration

Revision ID: 5d5faa1a9385
Revises: 
Create Date: 2025-11-01 16:56:50.641129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5faa1a9385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('scrape',
    sa.Column('scrape_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scrape_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('friend_a', sa.BigInteger(), nullable=False),
    sa.Column('friend_b', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['friend_a'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['friend_b'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('friend_a', 'friend_b')
    )
    op.create_table('group_member',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('org',
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('request',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.org_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('pledge',
    sa.Column('pledge_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('scrape_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.scrape_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pledge_id')
    )
    op.create_table('promotes',
    sa.Column('promotes_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('scrape_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.scrape_id'], ),
    sa.PrimaryKeyConstraint('promotes_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotes')
    op.drop_table('pledge')
    op.drop_table('request')
    op.drop_table('org')
    op.drop_table('group_member')
    op.drop_table('friends')
    op.drop_table('user')
    op.drop_table('scrape')
    op.drop_table('group')
    # ### end Alembic commands ###
